#ifndef __ROSE_OSCILLATOR_PATCH_HPP__
#define __ROSE_OSCILLATOR_PATCH_HPP__

/**
 * Rose curve (rhodonea) is a curve in 2D space generated by
 * plotting a sine wave in polar coordinates. Think of it as multiplying
 * sine by a complex quadrature oscillator. More details at
 * http://xahlee.info/SpecialPlaneCurves_dir/Rose_dir/rose.html
 * 
 * For comparison, multiplying two real signals wood give us good old
 * ring modulatttion
 * 
 * Param A sets tuning, buttons choose submenu
 * 
 * Main menu:
 * - param B morphs a pure complex sine into a rose
 * - params C and D set harmonic relationtionship, where internal modulator
 * has frequency determind as C divided by D
 * - when D == 0, internal oscillator is freerunning and you can get
 * inharmonic partials. Getting close to harmonic ratio gives you beating effect.
 * 
 * Submenu 1 controls feedback in the oscillator:
 * - param B sets internal sine oscillator feedback. If your rose has two layers
 * of petals, this moves them relative to each other
 * - param C sets direction (polar phase) for complex oscillator's feedback. This
 * determines where feedback warping is directed.
 * - param D adds feedback to complex oscillator. This warps complex oscillator shape
 * towards one of the corners.
 * 
 * Submenu 2 includes 2 wavefolders:
 * - param B sets order for distortion based on Chebyshev polynomials. This can
 * radically change oscillator shape. See https://en.wikipedia.org/wiki/Chebyshev_polynomials
 * - param C sets wavefolding vector direction for second wavefolder
 * - param D adds wavefolding gain
 * 
 * Audio input 1 is pitch CV, input 2 is FM. Pitch CV can be quantized if you
 * rebuild patch with quantizer enabled.
 **/

#include "MultiOscillator.hpp"
#include "SineOscillator.h"
#include "SquareOscillator.hpp"
#include "TriangleOscillator.hpp"
#include "VoltsPerOctave.h"
#include "Quantizer.hpp"
#include "LockableValue.hpp"
#include "RoseOscillator.hpp"
#include "Resample.h"
#include "MultiProcessor.hpp"
#include "Wavefolder.hpp"
#include "ChebyshevPolynomial.hpp"
#include "DcBlockingFilter.h"


#define BASE_FREQ 55.f
#define MAX_FM_AMOUNT 0.1f
//#define EXT_FM
#define MAX_RATIO 16
#define CHEB_ORDER 6

//#define QUANTIZER Quantizer12TET
// Uncomment to quantize

#define P_TUNE      PARAMETER_A
#define P_HARMONICS PARAMETER_B
#define P_MULT      PARAMETER_C
#define P_DIV       PARAMETER_D
#define P_FEEDBACK1 PARAMETER_AA
#define P_FB2_DIR   PARAMETER_AB
#define P_FB2_MAG   PARAMETER_AC
#define P_FOLD      PARAMETER_AD
#define P_DIR       PARAMETER_AE
#define P_MAG       PARAMETER_AF
#define P_CHAOS_X   PARAMETER_F
#define P_CHAOS_LFO PARAMETER_G

using SmoothParam = LockableValue<SmoothValue<float>, float>;
using StiffParam = LockableValue<StiffValue<float>, float>;
using RatioQuantizer = Quantizer<MAX_RATIO, true>;

class ModOscillator : public MultiOscillator {
public:
    ModOscillator(float freq, float sr = 48000)
        : MultiOscillator(3, freq, sr)
        , osc0(freq, sr)
        , osc1(freq, sr)
        , osc2(freq, sr) {
        addOscillator(&osc0);
        addOscillator(&osc1);
        addOscillator(&osc2);
    }

private:
    SquareOscillator osc0;
    SineOscillator osc1;
    TriangleOscillator osc2;
};


using StereoWavefolder = MultiProcessor<Wavefolder<HardClipper>, 2>;
using StereoCheb = MultiProcessor<MorphingChebyshevPolynomial<false>, 2>;
using StereoDc = MultiProcessor<DcBlockingFilter, 2>;

class RoseLichPatch : public Patch {
private:
    RoseOscillator osc;
    ModOscillator mod;
    SineOscillator mod_lfo;
    DcBlockingFilter dc_fm;

    float attr_x = 0.0, attr_y = 0.0;
    const float attr_a = -0.827;
    const float attr_b = -1.637;
    const float attr_c = 1.659;
    const float attr_d = -0.943;
    ComplexFloat cmp_offset;
    ComplexFloat sample;
#ifdef QUANTIZER
    QUANTIZER quantizer;
#endif
    bool isModeA = false, isModeB = false;
    float fm_ratio;
    float fm_amount;
    VoltsPerOctave hz;
    // QuadraturePhaser* phaser;
    StereoWavefolder wavefolder;
    StereoCheb cheb;
    StereoDc dc;
    float lfo_sample;
    SmoothParam p_feedback = SmoothParam(0.01);
    StiffParam p_divisor = StiffParam(1.f / float(MAX_RATIO + 1));
    StiffParam p_multiplier = StiffParam(1.f / float(MAX_RATIO));
    SmoothParam p_ratio = SmoothParam(0.01);
    SmoothParam p_harmonics = SmoothParam(0.01);
    SmoothParam p_fb_direction = SmoothParam(0.01);
    SmoothParam p_fb_magnitude = SmoothParam(0.01);
    SmoothParam p_fold = SmoothParam(0.01);
    SmoothParam p_direction = SmoothParam(0.01);
    SmoothParam p_magnitude = SmoothParam(0.01);
    FloatArray env_copy;
    inline float crossfade(float a, float b, float fade) {
        return a * fade + b * (1 - fade);
    }

public:
    RoseLichPatch()
        : mod_lfo(0.75, getSampleRate() / getBlockSize())
        , osc(BASE_FREQ, getSampleRate())
        , mod(BASE_FREQ, getSampleRate())
    {
        registerParameter(P_TUNE, "Tune");
        setParameterValue(P_TUNE, 0.5f);
        registerParameter(P_HARMONICS, "Harmonics");
        registerParameter(P_MULT, "Multiplier");
        registerParameter(P_DIV, "Divisor");
        registerParameter(P_FEEDBACK1, "Feedback1");
        setParameterValue(P_FEEDBACK1, 0.f);
        registerParameter(P_FB2_MAG, "Feedbaack2 Magnitude");
        registerParameter(P_FB2_DIR, "Feedbaack2 Phase");        
        registerParameter(P_FOLD, "Chebyshaper");
        setParameterValue(P_FOLD, 0.f);
        registerParameter(P_DIR, "Direction");
        setParameterValue(P_DIR, 0.f);
        registerParameter(P_MAG, "Offset");
        setParameterValue(P_MAG, 0.f);
        registerParameter(P_CHAOS_X, "ChaosX>");
        registerParameter(P_CHAOS_LFO, "ChaoLFO>");

        p_feedback.rawValue().lambda = 0.96;
        p_multiplier.rawValue().delta = (1.f / float(MAX_RATIO + 1));
        p_divisor.rawValue().delta = (1.f / float(MAX_RATIO + 2));
        p_harmonics.rawValue().lambda = 0.96;
        p_fb_direction.rawValue().lambda = 0.96;
        p_fb_magnitude.rawValue().lambda = 0.96;
        p_fold.rawValue().lambda = 0.99;
        p_direction.rawValue().lambda = 0.96;
        p_magnitude.rawValue().lambda = 0.96;

        setButton(BUTTON_A, false, 0);
        setButton(BUTTON_B, false, 0);
        cheb.get(0).setMaxOrder(CHEB_ORDER);
        cheb.get(1).setMaxOrder(CHEB_ORDER);
        cheb.get(0).setOffset(1);
        cheb.get(1).setOffset(1);
//        lockAll();
    }

    ~RoseLichPatch() {
    }

    void lockAll() {
        p_feedback.setLock(true);
        p_ratio.setLock(true);
        p_multiplier.setLock(true);
        p_divisor.setLock(true);
        p_harmonics.setLock(true);
        p_fb_direction.setLock(true);
        p_fb_magnitude.setLock(true);
        p_fold.setLock(true);
        p_direction.setLock(true);
        p_magnitude.setLock(true);
    }

    void buttonChanged(PatchButtonId bid, uint16_t value, uint16_t samples) override {
        switch (bid) {
        case BUTTON_A:
            if (value)
                isModeA = !isModeA;
            setButton(BUTTON_A, isModeA, 0);
            if (isModeA) {
                setButton(BUTTON_B, false, 0);
                isModeB = false;
            }
            lockAll();
            break;
        case BUTTON_B:
            if (value)
                isModeB = !isModeB;
            setButton(BUTTON_B, isModeB, 0);
            if (isModeB) {
                setButton(BUTTON_A, false, 0);
                isModeA = false;
            }
            lockAll();
            break;
        default:
            break;
        }
    }

    void processAttractor(float chaos) {
        float old_x = attr_x, old_y = attr_y;
        attr_x = sin(attr_a * old_y) - cos(attr_b * old_x);
        attr_y = sin(attr_c * old_x) - cos(attr_d * old_y);
        lfo_sample = mod_lfo.generate(attr_y * chaos * 0.02);
    }

    void processAudio(AudioBuffer& buffer) {
        // CV output
        processAttractor(1.0);
        setParameterValue(P_CHAOS_X, attr_x * 0.5 + 0.5);
        setParameterValue(P_CHAOS_LFO, lfo_sample * 0.5 + 0.5);
        setButton(BUTTON_C, lfo_sample >= 0.0);

        FloatArray left = buffer.getSamples(LEFT_CHANNEL);
        FloatArray right = buffer.getSamples(RIGHT_CHANNEL);
        dc_fm.process(right, right);
        right.multiply(MAX_FM_AMOUNT);

        // Tuning
        float tune = -4.0 + getParameterValue(P_TUNE) * 4.0;
#ifndef QUANTIZER
        hz.setTune(tune);
#endif
// Carrier / modulator frequency
#ifdef QUANTIZER
        float volts = quantizer.process(tune + hz.sampleToVolts(left[0]));
        float freq = hz.voltsToHertz(volts);
#else
        float freq = hz.getFrequency(left[0]);
#endif

        // Update params in FM settings
        if (isModeA) {
            setParameterValue(PARAMETER_AA, getParameterValue(PARAMETER_B));
            setParameterValue(PARAMETER_AB, getParameterValue(PARAMETER_C));
            setParameterValue(PARAMETER_AC, getParameterValue(PARAMETER_D));
        }
        else if (isModeB) {
            setParameterValue(PARAMETER_AD, getParameterValue(PARAMETER_B));
            setParameterValue(PARAMETER_AE, getParameterValue(PARAMETER_C));
            setParameterValue(PARAMETER_AF, getParameterValue(PARAMETER_D));
        }
        else {
            p_harmonics.update(getParameterValue(P_HARMONICS));
            p_multiplier.update(getParameterValue(P_MULT));
            p_divisor.update(getParameterValue(P_DIV));
            p_ratio.update(getParameterValue(P_MULT));
            int divisor = (MAX_RATIO + 1) * p_divisor.getValue();
            if (divisor == 0) {
                osc.setRatio(p_ratio.getValue() * MAX_RATIO);
            }
            else {                
                int multiplier = MAX_RATIO * p_multiplier.getValue() + 1;
                osc.setRatio(float(multiplier) / float(divisor));
            }
        }

        p_feedback.update(getParameterValue(P_FEEDBACK1) * 2.f - 1.f);
        p_fb_direction.update(getParameterValue(P_FB2_DIR));
        p_fb_magnitude.update(getParameterValue(P_FB2_MAG));

        p_fold.update(getParameterValue(P_FOLD));
        p_direction.update(getParameterValue(P_DIR));
        p_magnitude.update(getParameterValue(P_MAG));

        osc.setFrequency(freq);
        osc.setHarmonics(p_harmonics.getValue());
        osc.setFeedback1(p_feedback.getValue());
        osc.setFeedback2(p_fb_magnitude.getValue(), p_fb_direction.getValue() * M_PI * 4.f);

//        right.multiply(ext_fm_amt * MAX_FM_AMOUNT);
        right.add(left);

        osc.generate(buffer, right);
        
        // Chebyshev wavefolder
        float fold = p_fold.getValue();
        cheb.get(0).setMorph(fold);
        cheb.get(1).setMorph(fold);
        cheb.process(buffer, buffer);

        // Complex wavefolder
        float offset_phase = p_direction.getValue() * M_PI;
        float offset_mag = p_magnitude.getValue() * 3;
        cmp_offset.setPolar(offset_mag, offset_phase);

        left.multiply(1.f + abs(cmp_offset.re));
        right.multiply(1.f + abs(cmp_offset.im));
        wavefolder.process(buffer, buffer);

        dc.process(buffer, buffer);

    }
};
#endif
